//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDumps
    {
        public string TransportId { get; set; }
        public string ParkNumber { get; set; }
        public string TypeId { get; set; }
        public string ModelId { get; set; }
        public Nullable<double> LastLongitude { get; set; }
        public Nullable<double> LastLatitude { get; set; }
    }
}
